// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbXAEw6jScIv73Jhj4H2J6C2kxgwwYcfI',
    appId: '1:27169477102:web:6b3ab3200f677bfc253eff',
    messagingSenderId: '27169477102',
    projectId: 'wetherapp-6bb69',
    authDomain: 'wetherapp-6bb69.firebaseapp.com',
    storageBucket: 'wetherapp-6bb69.firebasestorage.app',
    measurementId: 'G-DECV6QCSXT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBGbQxhoev9ejNptnBI2Zb0tikj2Kl6Zyo',
    appId: '1:27169477102:android:cd165aa89d280c7e253eff',
    messagingSenderId: '27169477102',
    projectId: 'wetherapp-6bb69',
    storageBucket: 'wetherapp-6bb69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYy-yfOKSBfPmPLTmxE6nT3AeN_dNxTJE',
    appId: '1:27169477102:ios:032f403589b129f3253eff',
    messagingSenderId: '27169477102',
    projectId: 'wetherapp-6bb69',
    storageBucket: 'wetherapp-6bb69.firebasestorage.app',
    iosBundleId: 'com.example.testDig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYy-yfOKSBfPmPLTmxE6nT3AeN_dNxTJE',
    appId: '1:27169477102:ios:032f403589b129f3253eff',
    messagingSenderId: '27169477102',
    projectId: 'wetherapp-6bb69',
    storageBucket: 'wetherapp-6bb69.firebasestorage.app',
    iosBundleId: 'com.example.testDig',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbXAEw6jScIv73Jhj4H2J6C2kxgwwYcfI',
    appId: '1:27169477102:web:bd355886b681ac8d253eff',
    messagingSenderId: '27169477102',
    projectId: 'wetherapp-6bb69',
    authDomain: 'wetherapp-6bb69.firebaseapp.com',
    storageBucket: 'wetherapp-6bb69.firebasestorage.app',
    measurementId: 'G-VPTDP1X4K4',
  );
}
